//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.10 at 10:37:56 PM PST 
//


package com.actimizewebservice.api.actimize;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.actimizewebservice.api.actimize package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _RealTimeWSProviderRequestTitle_QNAME = new QName("http://www.actimizewebservice.com/api/actimize", "title");
    private final static QName _RealTimeWSProviderRequestIds_QNAME = new QName("http://www.actimizewebservice.com/api/actimize", "ids");
    private final static QName _RealTimeWSProviderRequestNationalities_QNAME = new QName("http://www.actimizewebservice.com/api/actimize", "nationalities");
    private final static QName _RealTimeWSProviderRequestAddresses_QNAME = new QName("http://www.actimizewebservice.com/api/actimize", "addresses");
    private final static QName _RealTimeWSProviderRequestAliases_QNAME = new QName("http://www.actimizewebservice.com/api/actimize", "aliases");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.actimizewebservice.api.actimize
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RealTimeWSProviderRequest.Ids.IdsInnerSet.RealTimeWSProviderIdsInnerSetTupleType }
     * 
     */
    public RealTimeWSProviderRequest.Ids.IdsInnerSet.RealTimeWSProviderIdsInnerSetTupleType createRealTimeWSProviderRequestIdsIdsInnerSetRealTimeWSProviderIdsInnerSetTupleType() {
        return new RealTimeWSProviderRequest.Ids.IdsInnerSet.RealTimeWSProviderIdsInnerSetTupleType();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderRequest.Ids }
     * 
     */
    public RealTimeWSProviderRequest.Ids createRealTimeWSProviderRequestIds() {
        return new RealTimeWSProviderRequest.Ids();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderRequest.Aliases }
     * 
     */
    public RealTimeWSProviderRequest.Aliases createRealTimeWSProviderRequestAliases() {
        return new RealTimeWSProviderRequest.Aliases();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderResponse }
     * 
     */
    public RealTimeWSProviderResponse createRealTimeWSProviderResponse() {
        return new RealTimeWSProviderResponse();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderResponse.Hits.HitsInnerSet }
     * 
     */
    public RealTimeWSProviderResponse.Hits.HitsInnerSet createRealTimeWSProviderResponseHitsHitsInnerSet() {
        return new RealTimeWSProviderResponse.Hits.HitsInnerSet();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderResponse.Hits.HitsInnerSet.RealTimeWSProviderHitsInnerSetTupleType }
     * 
     */
    public RealTimeWSProviderResponse.Hits.HitsInnerSet.RealTimeWSProviderHitsInnerSetTupleType createRealTimeWSProviderResponseHitsHitsInnerSetRealTimeWSProviderHitsInnerSetTupleType() {
        return new RealTimeWSProviderResponse.Hits.HitsInnerSet.RealTimeWSProviderHitsInnerSetTupleType();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderRequest.Addresses.AddressesInnerSet.RealTimeWSProviderAddressesInnerSetTupleType }
     * 
     */
    public RealTimeWSProviderRequest.Addresses.AddressesInnerSet.RealTimeWSProviderAddressesInnerSetTupleType createRealTimeWSProviderRequestAddressesAddressesInnerSetRealTimeWSProviderAddressesInnerSetTupleType() {
        return new RealTimeWSProviderRequest.Addresses.AddressesInnerSet.RealTimeWSProviderAddressesInnerSetTupleType();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderResponse.RealTimeWSProviderReturn }
     * 
     */
    public RealTimeWSProviderResponse.RealTimeWSProviderReturn createRealTimeWSProviderResponseRealTimeWSProviderReturn() {
        return new RealTimeWSProviderResponse.RealTimeWSProviderReturn();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderRequest.Nationalities.NationalitiesInnerSet.RealTimeWSProviderNationalitiesInnerSetTupleType }
     * 
     */
    public RealTimeWSProviderRequest.Nationalities.NationalitiesInnerSet.RealTimeWSProviderNationalitiesInnerSetTupleType createRealTimeWSProviderRequestNationalitiesNationalitiesInnerSetRealTimeWSProviderNationalitiesInnerSetTupleType() {
        return new RealTimeWSProviderRequest.Nationalities.NationalitiesInnerSet.RealTimeWSProviderNationalitiesInnerSetTupleType();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderRequest.Ids.IdsInnerSet }
     * 
     */
    public RealTimeWSProviderRequest.Ids.IdsInnerSet createRealTimeWSProviderRequestIdsIdsInnerSet() {
        return new RealTimeWSProviderRequest.Ids.IdsInnerSet();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderRequest.Addresses }
     * 
     */
    public RealTimeWSProviderRequest.Addresses createRealTimeWSProviderRequestAddresses() {
        return new RealTimeWSProviderRequest.Addresses();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderRequest.Names }
     * 
     */
    public RealTimeWSProviderRequest.Names createRealTimeWSProviderRequestNames() {
        return new RealTimeWSProviderRequest.Names();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderRequest.Nationalities }
     * 
     */
    public RealTimeWSProviderRequest.Nationalities createRealTimeWSProviderRequestNationalities() {
        return new RealTimeWSProviderRequest.Nationalities();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderRequest.Aliases.AliasesInnerSet.RealTimeWSProviderAliasesInnerSetTupleType }
     * 
     */
    public RealTimeWSProviderRequest.Aliases.AliasesInnerSet.RealTimeWSProviderAliasesInnerSetTupleType createRealTimeWSProviderRequestAliasesAliasesInnerSetRealTimeWSProviderAliasesInnerSetTupleType() {
        return new RealTimeWSProviderRequest.Aliases.AliasesInnerSet.RealTimeWSProviderAliasesInnerSetTupleType();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderRequest }
     * 
     */
    public RealTimeWSProviderRequest createRealTimeWSProviderRequest() {
        return new RealTimeWSProviderRequest();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderRequest.Addresses.AddressesInnerSet }
     * 
     */
    public RealTimeWSProviderRequest.Addresses.AddressesInnerSet createRealTimeWSProviderRequestAddressesAddressesInnerSet() {
        return new RealTimeWSProviderRequest.Addresses.AddressesInnerSet();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderResponse.Hits }
     * 
     */
    public RealTimeWSProviderResponse.Hits createRealTimeWSProviderResponseHits() {
        return new RealTimeWSProviderResponse.Hits();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderRequest.Nationalities.NationalitiesInnerSet }
     * 
     */
    public RealTimeWSProviderRequest.Nationalities.NationalitiesInnerSet createRealTimeWSProviderRequestNationalitiesNationalitiesInnerSet() {
        return new RealTimeWSProviderRequest.Nationalities.NationalitiesInnerSet();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderRequest.Aliases.AliasesInnerSet }
     * 
     */
    public RealTimeWSProviderRequest.Aliases.AliasesInnerSet createRealTimeWSProviderRequestAliasesAliasesInnerSet() {
        return new RealTimeWSProviderRequest.Aliases.AliasesInnerSet();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.actimizewebservice.com/api/actimize", name = "title", scope = RealTimeWSProviderRequest.class)
    public JAXBElement<String> createRealTimeWSProviderRequestTitle(String value) {
        return new JAXBElement<String>(_RealTimeWSProviderRequestTitle_QNAME, String.class, RealTimeWSProviderRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RealTimeWSProviderRequest.Ids }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.actimizewebservice.com/api/actimize", name = "ids", scope = RealTimeWSProviderRequest.class)
    public JAXBElement<RealTimeWSProviderRequest.Ids> createRealTimeWSProviderRequestIds(RealTimeWSProviderRequest.Ids value) {
        return new JAXBElement<RealTimeWSProviderRequest.Ids>(_RealTimeWSProviderRequestIds_QNAME, RealTimeWSProviderRequest.Ids.class, RealTimeWSProviderRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RealTimeWSProviderRequest.Nationalities }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.actimizewebservice.com/api/actimize", name = "nationalities", scope = RealTimeWSProviderRequest.class)
    public JAXBElement<RealTimeWSProviderRequest.Nationalities> createRealTimeWSProviderRequestNationalities(RealTimeWSProviderRequest.Nationalities value) {
        return new JAXBElement<RealTimeWSProviderRequest.Nationalities>(_RealTimeWSProviderRequestNationalities_QNAME, RealTimeWSProviderRequest.Nationalities.class, RealTimeWSProviderRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RealTimeWSProviderRequest.Addresses }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.actimizewebservice.com/api/actimize", name = "addresses", scope = RealTimeWSProviderRequest.class)
    public JAXBElement<RealTimeWSProviderRequest.Addresses> createRealTimeWSProviderRequestAddresses(RealTimeWSProviderRequest.Addresses value) {
        return new JAXBElement<RealTimeWSProviderRequest.Addresses>(_RealTimeWSProviderRequestAddresses_QNAME, RealTimeWSProviderRequest.Addresses.class, RealTimeWSProviderRequest.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RealTimeWSProviderRequest.Aliases }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.actimizewebservice.com/api/actimize", name = "aliases", scope = RealTimeWSProviderRequest.class)
    public JAXBElement<RealTimeWSProviderRequest.Aliases> createRealTimeWSProviderRequestAliases(RealTimeWSProviderRequest.Aliases value) {
        return new JAXBElement<RealTimeWSProviderRequest.Aliases>(_RealTimeWSProviderRequestAliases_QNAME, RealTimeWSProviderRequest.Aliases.class, RealTimeWSProviderRequest.class, value);
    }

}
