//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.23 at 03:32:07 PM PST 
//


package com.actimizewebservice.api.actimize;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.actimizewebservice.api.actimize package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.actimizewebservice.api.actimize
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RealTimeWSProviderResponse.Hits.HitsInnerSet }
     * 
     */
    public RealTimeWSProviderResponse.Hits.HitsInnerSet createRealTimeWSProviderResponseHitsHitsInnerSet() {
        return new RealTimeWSProviderResponse.Hits.HitsInnerSet();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderResponse.RealTimeWSProviderReturn }
     * 
     */
    public RealTimeWSProviderResponse.RealTimeWSProviderReturn createRealTimeWSProviderResponseRealTimeWSProviderReturn() {
        return new RealTimeWSProviderResponse.RealTimeWSProviderReturn();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderResponse }
     * 
     */
    public RealTimeWSProviderResponse createRealTimeWSProviderResponse() {
        return new RealTimeWSProviderResponse();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderRequest }
     * 
     */
    public RealTimeWSProviderRequest createRealTimeWSProviderRequest() {
        return new RealTimeWSProviderRequest();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderResponse.Hits.HitsInnerSet.RealTimeWSProviderHitsInnerSetTupleType }
     * 
     */
    public RealTimeWSProviderResponse.Hits.HitsInnerSet.RealTimeWSProviderHitsInnerSetTupleType createRealTimeWSProviderResponseHitsHitsInnerSetRealTimeWSProviderHitsInnerSetTupleType() {
        return new RealTimeWSProviderResponse.Hits.HitsInnerSet.RealTimeWSProviderHitsInnerSetTupleType();
    }

    /**
     * Create an instance of {@link RealTimeWSProviderResponse.Hits }
     * 
     */
    public RealTimeWSProviderResponse.Hits createRealTimeWSProviderResponseHits() {
        return new RealTimeWSProviderResponse.Hits();
    }

}
