//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.08.10 at 10:37:56 PM PST 
//


package com.actimizewebservice.api.actimize;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="requestId" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="searchDefinitionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="generateAlert" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="enableSuppression" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="partyType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="partyKey" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="names">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="fullName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="maidenName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="aliases" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="aliases_InnerSet">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RealTimeWSProvider_Aliases_InnerSet_TupleType">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="fullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="maidenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ids" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ids_InnerSet">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RealTimeWSProvider_Ids_InnerSet_TupleType">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="idCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="idType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="idValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="addresses" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="addresses_InnerSet">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RealTimeWSProvider_Addresses_InnerSet_TupleType">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="postalCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                                       &lt;element name="stateProvince" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="street1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="street2" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dateOfBirth" type="{http://www.w3.org/2001/XMLSchema}gMonthDay" minOccurs="0"/>
 *         &lt;element name="yearOfBirth" type="{http://www.w3.org/2001/XMLSchema}gYear" minOccurs="0"/>
 *         &lt;element name="locationOfBirth" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="countryOfBirth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nationalities" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nationalities_InnerSet">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RealTimeWSProvider_Nationalities_InnerSet_TupleType">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="gender" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="alertBusinessUnit" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="customFields" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="18"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "requestId",
    "searchDefinitionId",
    "generateAlert",
    "enableSuppression",
    "partyType",
    "partyKey",
    "names",
    "aliases",
    "ids",
    "addresses",
    "dateOfBirth",
    "yearOfBirth",
    "locationOfBirth",
    "countryOfBirth",
    "nationalities",
    "gender",
    "title",
    "alertBusinessUnit",
    "customFields"
})
@XmlRootElement(name = "RealTimeWSProviderRequest")
public class RealTimeWSProviderRequest {

    protected Integer requestId;
    @XmlElement(required = true)
    protected String searchDefinitionId;
    protected boolean generateAlert;
    protected boolean enableSuppression;
    @XmlElement(required = true)
    protected String partyType;
    @XmlElement(required = true)
    protected String partyKey;
    @XmlElement(required = true)
    protected RealTimeWSProviderRequest.Names names;
    @XmlElementRef(name = "aliases", namespace = "http://www.actimizewebservice.com/api/actimize", type = JAXBElement.class)
    protected JAXBElement<RealTimeWSProviderRequest.Aliases> aliases;
    @XmlElementRef(name = "ids", namespace = "http://www.actimizewebservice.com/api/actimize", type = JAXBElement.class)
    protected JAXBElement<RealTimeWSProviderRequest.Ids> ids;
    @XmlElementRef(name = "addresses", namespace = "http://www.actimizewebservice.com/api/actimize", type = JAXBElement.class)
    protected JAXBElement<RealTimeWSProviderRequest.Addresses> addresses;
    @XmlSchemaType(name = "gMonthDay")
    protected XMLGregorianCalendar dateOfBirth;
    @XmlSchemaType(name = "gYear")
    protected XMLGregorianCalendar yearOfBirth;
    protected String locationOfBirth;
    @XmlElement(required = true)
    protected String countryOfBirth;
    @XmlElementRef(name = "nationalities", namespace = "http://www.actimizewebservice.com/api/actimize", type = JAXBElement.class)
    protected JAXBElement<RealTimeWSProviderRequest.Nationalities> nationalities;
    @XmlElement(required = true)
    protected String gender;
    @XmlElementRef(name = "title", namespace = "http://www.actimizewebservice.com/api/actimize", type = JAXBElement.class)
    protected JAXBElement<String> title;
    @XmlElement(required = true)
    protected String alertBusinessUnit;
    @XmlElement(required = true)
    protected List<String> customFields;

    /**
     * Gets the value of the requestId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getRequestId() {
        return requestId;
    }

    /**
     * Sets the value of the requestId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setRequestId(Integer value) {
        this.requestId = value;
    }

    /**
     * Gets the value of the searchDefinitionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchDefinitionId() {
        return searchDefinitionId;
    }

    /**
     * Sets the value of the searchDefinitionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchDefinitionId(String value) {
        this.searchDefinitionId = value;
    }

    /**
     * Gets the value of the generateAlert property.
     * 
     */
    public boolean isGenerateAlert() {
        return generateAlert;
    }

    /**
     * Sets the value of the generateAlert property.
     * 
     */
    public void setGenerateAlert(boolean value) {
        this.generateAlert = value;
    }

    /**
     * Gets the value of the enableSuppression property.
     * 
     */
    public boolean isEnableSuppression() {
        return enableSuppression;
    }

    /**
     * Sets the value of the enableSuppression property.
     * 
     */
    public void setEnableSuppression(boolean value) {
        this.enableSuppression = value;
    }

    /**
     * Gets the value of the partyType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyType() {
        return partyType;
    }

    /**
     * Sets the value of the partyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyType(String value) {
        this.partyType = value;
    }

    /**
     * Gets the value of the partyKey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPartyKey() {
        return partyKey;
    }

    /**
     * Sets the value of the partyKey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPartyKey(String value) {
        this.partyKey = value;
    }

    /**
     * Gets the value of the names property.
     * 
     * @return
     *     possible object is
     *     {@link RealTimeWSProviderRequest.Names }
     *     
     */
    public RealTimeWSProviderRequest.Names getNames() {
        return names;
    }

    /**
     * Sets the value of the names property.
     * 
     * @param value
     *     allowed object is
     *     {@link RealTimeWSProviderRequest.Names }
     *     
     */
    public void setNames(RealTimeWSProviderRequest.Names value) {
        this.names = value;
    }

    /**
     * Gets the value of the aliases property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RealTimeWSProviderRequest.Aliases }{@code >}
     *     
     */
    public JAXBElement<RealTimeWSProviderRequest.Aliases> getAliases() {
        return aliases;
    }

    /**
     * Sets the value of the aliases property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RealTimeWSProviderRequest.Aliases }{@code >}
     *     
     */
    public void setAliases(JAXBElement<RealTimeWSProviderRequest.Aliases> value) {
        this.aliases = ((JAXBElement<RealTimeWSProviderRequest.Aliases> ) value);
    }

    /**
     * Gets the value of the ids property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RealTimeWSProviderRequest.Ids }{@code >}
     *     
     */
    public JAXBElement<RealTimeWSProviderRequest.Ids> getIds() {
        return ids;
    }

    /**
     * Sets the value of the ids property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RealTimeWSProviderRequest.Ids }{@code >}
     *     
     */
    public void setIds(JAXBElement<RealTimeWSProviderRequest.Ids> value) {
        this.ids = ((JAXBElement<RealTimeWSProviderRequest.Ids> ) value);
    }

    /**
     * Gets the value of the addresses property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RealTimeWSProviderRequest.Addresses }{@code >}
     *     
     */
    public JAXBElement<RealTimeWSProviderRequest.Addresses> getAddresses() {
        return addresses;
    }

    /**
     * Sets the value of the addresses property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RealTimeWSProviderRequest.Addresses }{@code >}
     *     
     */
    public void setAddresses(JAXBElement<RealTimeWSProviderRequest.Addresses> value) {
        this.addresses = ((JAXBElement<RealTimeWSProviderRequest.Addresses> ) value);
    }

    /**
     * Gets the value of the dateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDateOfBirth() {
        return dateOfBirth;
    }

    /**
     * Sets the value of the dateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDateOfBirth(XMLGregorianCalendar value) {
        this.dateOfBirth = value;
    }

    /**
     * Gets the value of the yearOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getYearOfBirth() {
        return yearOfBirth;
    }

    /**
     * Sets the value of the yearOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setYearOfBirth(XMLGregorianCalendar value) {
        this.yearOfBirth = value;
    }

    /**
     * Gets the value of the locationOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocationOfBirth() {
        return locationOfBirth;
    }

    /**
     * Sets the value of the locationOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocationOfBirth(String value) {
        this.locationOfBirth = value;
    }

    /**
     * Gets the value of the countryOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfBirth() {
        return countryOfBirth;
    }

    /**
     * Sets the value of the countryOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfBirth(String value) {
        this.countryOfBirth = value;
    }

    /**
     * Gets the value of the nationalities property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link RealTimeWSProviderRequest.Nationalities }{@code >}
     *     
     */
    public JAXBElement<RealTimeWSProviderRequest.Nationalities> getNationalities() {
        return nationalities;
    }

    /**
     * Sets the value of the nationalities property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link RealTimeWSProviderRequest.Nationalities }{@code >}
     *     
     */
    public void setNationalities(JAXBElement<RealTimeWSProviderRequest.Nationalities> value) {
        this.nationalities = ((JAXBElement<RealTimeWSProviderRequest.Nationalities> ) value);
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setTitle(JAXBElement<String> value) {
        this.title = ((JAXBElement<String> ) value);
    }

    /**
     * Gets the value of the alertBusinessUnit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlertBusinessUnit() {
        return alertBusinessUnit;
    }

    /**
     * Sets the value of the alertBusinessUnit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlertBusinessUnit(String value) {
        this.alertBusinessUnit = value;
    }

    /**
     * Gets the value of the customFields property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the customFields property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCustomFields().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getCustomFields() {
        if (customFields == null) {
            customFields = new ArrayList<String>();
        }
        return this.customFields;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="addresses_InnerSet">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RealTimeWSProvider_Addresses_InnerSet_TupleType">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="postalCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *                             &lt;element name="stateProvince" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="street1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="street2" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "addressesInnerSet"
    })
    public static class Addresses {

        @XmlElement(name = "addresses_InnerSet", required = true)
        protected RealTimeWSProviderRequest.Addresses.AddressesInnerSet addressesInnerSet;

        /**
         * Gets the value of the addressesInnerSet property.
         * 
         * @return
         *     possible object is
         *     {@link RealTimeWSProviderRequest.Addresses.AddressesInnerSet }
         *     
         */
        public RealTimeWSProviderRequest.Addresses.AddressesInnerSet getAddressesInnerSet() {
            return addressesInnerSet;
        }

        /**
         * Sets the value of the addressesInnerSet property.
         * 
         * @param value
         *     allowed object is
         *     {@link RealTimeWSProviderRequest.Addresses.AddressesInnerSet }
         *     
         */
        public void setAddressesInnerSet(RealTimeWSProviderRequest.Addresses.AddressesInnerSet value) {
            this.addressesInnerSet = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RealTimeWSProvider_Addresses_InnerSet_TupleType">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="postalCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *                   &lt;element name="stateProvince" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="street1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="street2" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "realTimeWSProviderAddressesInnerSetTupleType"
        })
        public static class AddressesInnerSet {

            @XmlElement(name = "RealTimeWSProvider_Addresses_InnerSet_TupleType", required = true)
            protected RealTimeWSProviderRequest.Addresses.AddressesInnerSet.RealTimeWSProviderAddressesInnerSetTupleType realTimeWSProviderAddressesInnerSetTupleType;

            /**
             * Gets the value of the realTimeWSProviderAddressesInnerSetTupleType property.
             * 
             * @return
             *     possible object is
             *     {@link RealTimeWSProviderRequest.Addresses.AddressesInnerSet.RealTimeWSProviderAddressesInnerSetTupleType }
             *     
             */
            public RealTimeWSProviderRequest.Addresses.AddressesInnerSet.RealTimeWSProviderAddressesInnerSetTupleType getRealTimeWSProviderAddressesInnerSetTupleType() {
                return realTimeWSProviderAddressesInnerSetTupleType;
            }

            /**
             * Sets the value of the realTimeWSProviderAddressesInnerSetTupleType property.
             * 
             * @param value
             *     allowed object is
             *     {@link RealTimeWSProviderRequest.Addresses.AddressesInnerSet.RealTimeWSProviderAddressesInnerSetTupleType }
             *     
             */
            public void setRealTimeWSProviderAddressesInnerSetTupleType(RealTimeWSProviderRequest.Addresses.AddressesInnerSet.RealTimeWSProviderAddressesInnerSetTupleType value) {
                this.realTimeWSProviderAddressesInnerSetTupleType = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="city" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="postalCode" type="{http://www.w3.org/2001/XMLSchema}int"/>
             *         &lt;element name="stateProvince" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="street1" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="street2" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "city",
                "country",
                "postalCode",
                "stateProvince",
                "street1",
                "street2"
            })
            public static class RealTimeWSProviderAddressesInnerSetTupleType {

                @XmlElement(required = true)
                protected String city;
                @XmlElement(required = true)
                protected String country;
                protected int postalCode;
                @XmlElement(required = true)
                protected String stateProvince;
                @XmlElement(required = true)
                protected String street1;
                @XmlElement(required = true)
                protected String street2;

                /**
                 * Gets the value of the city property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCity() {
                    return city;
                }

                /**
                 * Sets the value of the city property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCity(String value) {
                    this.city = value;
                }

                /**
                 * Gets the value of the country property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCountry() {
                    return country;
                }

                /**
                 * Sets the value of the country property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCountry(String value) {
                    this.country = value;
                }

                /**
                 * Gets the value of the postalCode property.
                 * 
                 */
                public int getPostalCode() {
                    return postalCode;
                }

                /**
                 * Sets the value of the postalCode property.
                 * 
                 */
                public void setPostalCode(int value) {
                    this.postalCode = value;
                }

                /**
                 * Gets the value of the stateProvince property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStateProvince() {
                    return stateProvince;
                }

                /**
                 * Sets the value of the stateProvince property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStateProvince(String value) {
                    this.stateProvince = value;
                }

                /**
                 * Gets the value of the street1 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStreet1() {
                    return street1;
                }

                /**
                 * Sets the value of the street1 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStreet1(String value) {
                    this.street1 = value;
                }

                /**
                 * Gets the value of the street2 property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getStreet2() {
                    return street2;
                }

                /**
                 * Sets the value of the street2 property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setStreet2(String value) {
                    this.street2 = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="aliases_InnerSet">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RealTimeWSProvider_Aliases_InnerSet_TupleType">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="fullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="maidenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "aliasesInnerSet"
    })
    public static class Aliases {

        @XmlElement(name = "aliases_InnerSet", required = true)
        protected RealTimeWSProviderRequest.Aliases.AliasesInnerSet aliasesInnerSet;

        /**
         * Gets the value of the aliasesInnerSet property.
         * 
         * @return
         *     possible object is
         *     {@link RealTimeWSProviderRequest.Aliases.AliasesInnerSet }
         *     
         */
        public RealTimeWSProviderRequest.Aliases.AliasesInnerSet getAliasesInnerSet() {
            return aliasesInnerSet;
        }

        /**
         * Sets the value of the aliasesInnerSet property.
         * 
         * @param value
         *     allowed object is
         *     {@link RealTimeWSProviderRequest.Aliases.AliasesInnerSet }
         *     
         */
        public void setAliasesInnerSet(RealTimeWSProviderRequest.Aliases.AliasesInnerSet value) {
            this.aliasesInnerSet = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RealTimeWSProvider_Aliases_InnerSet_TupleType">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="fullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="maidenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "realTimeWSProviderAliasesInnerSetTupleType"
        })
        public static class AliasesInnerSet {

            @XmlElement(name = "RealTimeWSProvider_Aliases_InnerSet_TupleType", required = true)
            protected RealTimeWSProviderRequest.Aliases.AliasesInnerSet.RealTimeWSProviderAliasesInnerSetTupleType realTimeWSProviderAliasesInnerSetTupleType;

            /**
             * Gets the value of the realTimeWSProviderAliasesInnerSetTupleType property.
             * 
             * @return
             *     possible object is
             *     {@link RealTimeWSProviderRequest.Aliases.AliasesInnerSet.RealTimeWSProviderAliasesInnerSetTupleType }
             *     
             */
            public RealTimeWSProviderRequest.Aliases.AliasesInnerSet.RealTimeWSProviderAliasesInnerSetTupleType getRealTimeWSProviderAliasesInnerSetTupleType() {
                return realTimeWSProviderAliasesInnerSetTupleType;
            }

            /**
             * Sets the value of the realTimeWSProviderAliasesInnerSetTupleType property.
             * 
             * @param value
             *     allowed object is
             *     {@link RealTimeWSProviderRequest.Aliases.AliasesInnerSet.RealTimeWSProviderAliasesInnerSetTupleType }
             *     
             */
            public void setRealTimeWSProviderAliasesInnerSetTupleType(RealTimeWSProviderRequest.Aliases.AliasesInnerSet.RealTimeWSProviderAliasesInnerSetTupleType value) {
                this.realTimeWSProviderAliasesInnerSetTupleType = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="fullName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="maidenName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "firstName",
                "fullName",
                "lastName",
                "maidenName",
                "middleName"
            })
            public static class RealTimeWSProviderAliasesInnerSetTupleType {

                @XmlElement(required = true)
                protected String firstName;
                @XmlElement(required = true)
                protected String fullName;
                @XmlElement(required = true)
                protected String lastName;
                @XmlElement(required = true)
                protected String maidenName;
                @XmlElement(required = true)
                protected String middleName;

                /**
                 * Gets the value of the firstName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFirstName() {
                    return firstName;
                }

                /**
                 * Sets the value of the firstName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFirstName(String value) {
                    this.firstName = value;
                }

                /**
                 * Gets the value of the fullName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFullName() {
                    return fullName;
                }

                /**
                 * Sets the value of the fullName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFullName(String value) {
                    this.fullName = value;
                }

                /**
                 * Gets the value of the lastName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getLastName() {
                    return lastName;
                }

                /**
                 * Sets the value of the lastName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setLastName(String value) {
                    this.lastName = value;
                }

                /**
                 * Gets the value of the maidenName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMaidenName() {
                    return maidenName;
                }

                /**
                 * Sets the value of the maidenName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMaidenName(String value) {
                    this.maidenName = value;
                }

                /**
                 * Gets the value of the middleName property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getMiddleName() {
                    return middleName;
                }

                /**
                 * Sets the value of the middleName property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setMiddleName(String value) {
                    this.middleName = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ids_InnerSet">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RealTimeWSProvider_Ids_InnerSet_TupleType">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="idCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="idType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="idValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "idsInnerSet"
    })
    public static class Ids {

        @XmlElement(name = "ids_InnerSet", required = true)
        protected RealTimeWSProviderRequest.Ids.IdsInnerSet idsInnerSet;

        /**
         * Gets the value of the idsInnerSet property.
         * 
         * @return
         *     possible object is
         *     {@link RealTimeWSProviderRequest.Ids.IdsInnerSet }
         *     
         */
        public RealTimeWSProviderRequest.Ids.IdsInnerSet getIdsInnerSet() {
            return idsInnerSet;
        }

        /**
         * Sets the value of the idsInnerSet property.
         * 
         * @param value
         *     allowed object is
         *     {@link RealTimeWSProviderRequest.Ids.IdsInnerSet }
         *     
         */
        public void setIdsInnerSet(RealTimeWSProviderRequest.Ids.IdsInnerSet value) {
            this.idsInnerSet = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RealTimeWSProvider_Ids_InnerSet_TupleType">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="idCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="idType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="idValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "realTimeWSProviderIdsInnerSetTupleType"
        })
        public static class IdsInnerSet {

            @XmlElement(name = "RealTimeWSProvider_Ids_InnerSet_TupleType", required = true)
            protected RealTimeWSProviderRequest.Ids.IdsInnerSet.RealTimeWSProviderIdsInnerSetTupleType realTimeWSProviderIdsInnerSetTupleType;

            /**
             * Gets the value of the realTimeWSProviderIdsInnerSetTupleType property.
             * 
             * @return
             *     possible object is
             *     {@link RealTimeWSProviderRequest.Ids.IdsInnerSet.RealTimeWSProviderIdsInnerSetTupleType }
             *     
             */
            public RealTimeWSProviderRequest.Ids.IdsInnerSet.RealTimeWSProviderIdsInnerSetTupleType getRealTimeWSProviderIdsInnerSetTupleType() {
                return realTimeWSProviderIdsInnerSetTupleType;
            }

            /**
             * Sets the value of the realTimeWSProviderIdsInnerSetTupleType property.
             * 
             * @param value
             *     allowed object is
             *     {@link RealTimeWSProviderRequest.Ids.IdsInnerSet.RealTimeWSProviderIdsInnerSetTupleType }
             *     
             */
            public void setRealTimeWSProviderIdsInnerSetTupleType(RealTimeWSProviderRequest.Ids.IdsInnerSet.RealTimeWSProviderIdsInnerSetTupleType value) {
                this.realTimeWSProviderIdsInnerSetTupleType = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="idCountry" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="idType" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="idValue" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "idCountry",
                "idType",
                "idValue"
            })
            public static class RealTimeWSProviderIdsInnerSetTupleType {

                @XmlElement(required = true)
                protected String idCountry;
                @XmlElement(required = true)
                protected String idType;
                @XmlElement(required = true)
                protected String idValue;

                /**
                 * Gets the value of the idCountry property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIdCountry() {
                    return idCountry;
                }

                /**
                 * Sets the value of the idCountry property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIdCountry(String value) {
                    this.idCountry = value;
                }

                /**
                 * Gets the value of the idType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIdType() {
                    return idType;
                }

                /**
                 * Sets the value of the idType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIdType(String value) {
                    this.idType = value;
                }

                /**
                 * Gets the value of the idValue property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getIdValue() {
                    return idValue;
                }

                /**
                 * Sets the value of the idValue property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setIdValue(String value) {
                    this.idValue = value;
                }

            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="firstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="fullName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="lastName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="maidenName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="middleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "firstName",
        "fullName",
        "lastName",
        "maidenName",
        "middleName"
    })
    public static class Names {

        protected String firstName;
        protected String fullName;
        protected String lastName;
        protected String maidenName;
        protected String middleName;

        /**
         * Gets the value of the firstName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFirstName() {
            return firstName;
        }

        /**
         * Sets the value of the firstName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFirstName(String value) {
            this.firstName = value;
        }

        /**
         * Gets the value of the fullName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFullName() {
            return fullName;
        }

        /**
         * Sets the value of the fullName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFullName(String value) {
            this.fullName = value;
        }

        /**
         * Gets the value of the lastName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLastName() {
            return lastName;
        }

        /**
         * Sets the value of the lastName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLastName(String value) {
            this.lastName = value;
        }

        /**
         * Gets the value of the maidenName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMaidenName() {
            return maidenName;
        }

        /**
         * Sets the value of the maidenName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMaidenName(String value) {
            this.maidenName = value;
        }

        /**
         * Gets the value of the middleName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMiddleName() {
            return middleName;
        }

        /**
         * Sets the value of the middleName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMiddleName(String value) {
            this.middleName = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nationalities_InnerSet">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RealTimeWSProvider_Nationalities_InnerSet_TupleType">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nationalitiesInnerSet"
    })
    public static class Nationalities {

        @XmlElement(name = "nationalities_InnerSet", required = true)
        protected RealTimeWSProviderRequest.Nationalities.NationalitiesInnerSet nationalitiesInnerSet;

        /**
         * Gets the value of the nationalitiesInnerSet property.
         * 
         * @return
         *     possible object is
         *     {@link RealTimeWSProviderRequest.Nationalities.NationalitiesInnerSet }
         *     
         */
        public RealTimeWSProviderRequest.Nationalities.NationalitiesInnerSet getNationalitiesInnerSet() {
            return nationalitiesInnerSet;
        }

        /**
         * Sets the value of the nationalitiesInnerSet property.
         * 
         * @param value
         *     allowed object is
         *     {@link RealTimeWSProviderRequest.Nationalities.NationalitiesInnerSet }
         *     
         */
        public void setNationalitiesInnerSet(RealTimeWSProviderRequest.Nationalities.NationalitiesInnerSet value) {
            this.nationalitiesInnerSet = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RealTimeWSProvider_Nationalities_InnerSet_TupleType">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "realTimeWSProviderNationalitiesInnerSetTupleType"
        })
        public static class NationalitiesInnerSet {

            @XmlElement(name = "RealTimeWSProvider_Nationalities_InnerSet_TupleType", required = true)
            protected RealTimeWSProviderRequest.Nationalities.NationalitiesInnerSet.RealTimeWSProviderNationalitiesInnerSetTupleType realTimeWSProviderNationalitiesInnerSetTupleType;

            /**
             * Gets the value of the realTimeWSProviderNationalitiesInnerSetTupleType property.
             * 
             * @return
             *     possible object is
             *     {@link RealTimeWSProviderRequest.Nationalities.NationalitiesInnerSet.RealTimeWSProviderNationalitiesInnerSetTupleType }
             *     
             */
            public RealTimeWSProviderRequest.Nationalities.NationalitiesInnerSet.RealTimeWSProviderNationalitiesInnerSetTupleType getRealTimeWSProviderNationalitiesInnerSetTupleType() {
                return realTimeWSProviderNationalitiesInnerSetTupleType;
            }

            /**
             * Sets the value of the realTimeWSProviderNationalitiesInnerSetTupleType property.
             * 
             * @param value
             *     allowed object is
             *     {@link RealTimeWSProviderRequest.Nationalities.NationalitiesInnerSet.RealTimeWSProviderNationalitiesInnerSetTupleType }
             *     
             */
            public void setRealTimeWSProviderNationalitiesInnerSetTupleType(RealTimeWSProviderRequest.Nationalities.NationalitiesInnerSet.RealTimeWSProviderNationalitiesInnerSetTupleType value) {
                this.realTimeWSProviderNationalitiesInnerSetTupleType = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "country"
            })
            public static class RealTimeWSProviderNationalitiesInnerSetTupleType {

                @XmlElement(required = true)
                protected String country;

                /**
                 * Gets the value of the country property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getCountry() {
                    return country;
                }

                /**
                 * Sets the value of the country property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setCountry(String value) {
                    this.country = value;
                }

            }

        }

    }

}
